[lint]
select = [
    "B",    # flake8-bugbear
    "C90",  # mccabe
    "E",    # pycodestyle
    "F",    # pyflakes
    "W",    # warnings
    "PL",   # pylint
    "I",    # isort
    "S",    # flake8-bandit
    "UP",   # pyupgrade
    "RUF",  # ruff
    "SIM",  # flake8-simplify
    "TRY",  # tryceratops
]
ignore = [
    "E203",
    "E501",
    "S101"
]
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true

[lint.mccabe]
max-complexity = 10

[lint.isort]
known-third-party = ["fastapi", "pydantic"]
