### Data mdt configuration
mdt:
  stars_column: stars             # Se usa antes del pipeline para crear target
  corr_threshold: 0.9
  importance_threshold: 0.4
  scoring: f1_weighted


### Data training configuration
model:
  classifier: xgboost.XGBClassifier
  params:
    n_estimators: 100
    max_depth: 4
    use_label_encoder: False
    eval_metric: logloss

target_column: target
test_size: 0.2
random_state: 42

### Data validate configuration
metric_thresholds:
  f1_macro: 0.70
  recall_macro: 0.70


outputs:
  model_path: models/final_model_v1.pkl
  metrics_path: models/metrics.parquet
